/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gbif.pipelines.models.taxonomy;

public enum NameRank {
  DOMAIN,
  REALM,
  SUBREALM,
  SUPERKINGDOM,
  KINGDOM,
  SUBKINGDOM,
  INFRAKINGDOM,
  SUPERPHYLUM,
  PHYLUM,
  SUBPHYLUM,
  INFRAPHYLUM,
  SUPERCLASS,
  CLASS,
  SUBCLASS,
  INFRACLASS,
  SUBTERCLASS,
  PARVCLASS,
  SUPERDIVISION,
  DIVISION,
  SUBDIVISION,
  INFRADIVISION,
  SUPERLEGION,
  LEGION,
  SUBLEGION,
  INFRALEGION,
  SUPERCOHORT,
  COHORT,
  SUBCOHORT,
  INFRACOHORT,
  GIGAORDER,
  MAGNORDER,
  GRANDORDER,
  MIRORDER,
  SUPERORDER,
  ORDER,
  NANORDER,
  HYPOORDER,
  MINORDER,
  SUBORDER,
  INFRAORDER,
  PARVORDER,
  MEGAFAMILY,
  GRANDFAMILY,
  SUPERFAMILY,
  EPIFAMILY,
  FAMILY,
  SUBFAMILY,
  INFRAFAMILY,
  SUPERTRIBE,
  TRIBE,
  SUBTRIBE,
  INFRATRIBE,
  SUPRAGENERIC_NAME,
  GENUS,
  SUBGENUS,
  INFRAGENUS,
  SUPERSECTION,
  SECTION,
  SUBSECTION,
  SUPERSERIES,
  SERIES,
  SUBSERIES,
  INFRAGENERIC_NAME,
  SPECIES_AGGREGATE,
  SPECIES,
  INFRASPECIFIC_NAME,
  GREX,
  SUBSPECIES,
  CULTIVAR_GROUP,
  CONVARIETY,
  INFRASUBSPECIFIC_NAME,
  PROLES,
  NATIO,
  ABERRATION,
  MORPH,
  VARIETY,
  SUBVARIETY,
  FORM,
  SUBFORM,
  PATHOVAR,
  BIOVAR,
  CHEMOVAR,
  MORPHOVAR,
  PHAGOVAR,
  SEROVAR,
  CHEMOFORM,
  FORMA_SPECIALIS,
  CULTIVAR,
  STRAIN,
  OTHER,
  UNRANKED;
}
